export const COMPLETIONS = [
    "SELECT",
    "FROM",
    "WHERE",
    "GROUP BY",
    "HAVING",
    "ORDER BY",
    "LIMIT",
    "OFFSET",
    "JOIN",
    "LEFT JOIN",
    "INNER JOIN",
    "ON",
    "AND",
    "OR",
    "NOT",
    "COUNT",
    "SUM",
    "BETWEEN",
    "IN",
    "WITH",
    "DISTINCT",
    "UNION ALL",
    "CREATE VIEW",
    "DROP VIEW",
    "DESCRIBE VIEW",
    "DESCRIBE TABLE",
    "SHOW VIEWS",
    "SHOW TABLES",
    "IF EXISTS",
    "IF NOT EXISTS",
    "OR REPLACE",
    "AS",
    "_time",
    "_stream",
    "_msg",
    "logs",
];
